export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const { goal = 'software engineer', signals = '' } = req.query;
  const g = goal.toLowerCase();
  const topSignals = signals ? signals.split(',').map(s => s.trim().toLowerCase()).filter(Boolean) : [];

  // Full article library keyed by topic
  const articleLibrary = {
    'software engineer': [
      { tag:'Roadmap', title:'The 2024 Software Engineering Roadmap: Zero to Hired', desc:'A step-by-step breakdown of what skills to learn, in what order, to land your first SWE role in under 12 months.', time:'8 min', url:'https://dev.to/search?q=software+engineer+roadmap+2024',
        content:`<p>Breaking into software engineering can feel overwhelming — there are a thousand resources and opinions. This guide cuts through the noise with what actually works in 2024.</p><p><strong>Step 1: HTML, CSS & JavaScript basics (6 weeks).</strong> Before frameworks, you need fluency in the fundamentals. freeCodeCamp and The Odin Project are free and excellent.</p><p><strong>Step 2: Pick one framework and go deep (8 weeks).</strong> React is the safest bet for employment. Don't jump between frameworks. Go deep on one.</p><p><strong>Step 3: Build 3 real projects (6 weeks).</strong> Nothing matters more to hiring managers than a portfolio that demonstrates real problem-solving. Make projects that solve actual problems you care about.</p><p><strong>Step 4: LeetCode fundamentals (4 weeks).</strong> You don't need to grind 500 problems. Learn the 10 core patterns — arrays, hashmaps, two pointers, sliding window, trees, graphs, dynamic programming basics, and binary search. That covers 80% of interviews.</p><p><strong>Step 5: Apply at 70% ready.</strong> You will never feel fully ready. Start applying and let the process teach you the rest.</p>` },
      { tag:'Interview', title:'I Did 200 LeetCode Problems. Here\'s What Actually Matters.', desc:'A senior engineer breaks down the exact patterns that show up in FAANG interviews — and which ones to skip.', time:'12 min', url:'https://dev.to/search?q=leetcode+patterns+interview',
        content:`<p>After 200 LeetCode problems and multiple FAANG offers, here's the truth: most of what you grind doesn't show up in interviews. Here's what does.</p><p><strong>The patterns that actually matter:</strong></p><p>Two Pointers — solves a huge range of array and string problems in O(n). If you see a sorted array and need to find a pair, two pointers is almost always the answer.</p><p>Sliding Window — any problem involving subarrays or substrings with a constraint. Fixed or variable window.</p><p>HashMap / HashSet — the single most useful tool in interviews. Turns O(n²) brute force into O(n) almost every time.</p><p>BFS / DFS — every tree and graph problem. BFS for shortest path, DFS for exploring all paths.</p><p>Dynamic Programming — the hardest to learn but often the easiest to recognize once you've seen enough. Look for overlapping subproblems and optimal substructure.</p><p><strong>What actually fails candidates</strong> isn't algorithm knowledge — it's communication. Talk through your thinking out loud. Interviewers care more about how you reason than whether you get to the optimal solution immediately.</p>` },
      { tag:'Career', title:'How I Went From Barista to $140K Engineer in 14 Months', desc:'A realistic account of what the self-taught journey actually looks like — including the parts that almost made me quit.', time:'10 min', url:'https://hashnode.com/search?q=self+taught+software+engineer',
        content:`<p>Fourteen months ago I was making $16/hour at a coffee shop. Today I'm a software engineer at a Series B startup earning $140K. Here's the unfiltered version of how that happened.</p><p><strong>Month 1-3: The honeymoon phase.</strong> I did freeCodeCamp every evening after shifts. It felt good. I was making progress. I didn't realize how much I didn't know yet.</p><p><strong>Month 4-6: The valley.</strong> I started building real projects and hit a wall. Nothing worked the way tutorials said it would. I almost quit twice. What kept me going was a Discord community of other self-taught developers in the same boat.</p><p><strong>Month 7-10: Things clicked.</strong> I can't explain exactly when it happened, but debugging stopped being terrifying. I started to actually enjoy the problem-solving. My first project that a real person used — a tool I built for my manager at the café — gave me more confidence than anything else.</p><p><strong>Month 11-14: The job hunt.</strong> I applied to 94 jobs. Got 12 phone screens. 4 technical interviews. 1 offer. The ratio feels brutal but it's normal. The offer came from a company I almost didn't apply to because I thought I wasn't qualified enough.</p><p>The most important lesson: qualify yourself by showing up consistently, not by waiting until you feel ready.</p>` },
    ],
    'entrepreneur': [
      { tag:'Mindset', title:'The Only Startup Advice That Actually Aged Well', desc:'Filtering 10 years of founder advice down to the 4 things that consistently turned out to be true.', time:'7 min', url:'https://medium.com/search?q=startup+advice+founder',
        content:`<p>I've been through two startups, one acquisition, and one failure. Here's the advice that actually held up over time.</p><p><strong>1. Talk to customers before building anything.</strong> Not to validate your idea — to find out what problem they actually have. These are often different things. Most failed startups built a solution to a problem nobody had urgently enough to pay for.</p><p><strong>2. Revenue solves almost every other problem.</strong> Funding, team morale, product direction, market validation — money coming in fixes or clarifies all of it. Optimize for getting paid as early as possible, even if the product isn't perfect.</p><p><strong>3. The team matters more than the idea.</strong> Ideas are worthless without execution. A great team with a mediocre idea will pivot to something better. A mediocre team with a great idea will execute it poorly.</p><p><strong>4. Do fewer things, better.</strong> Every startup I've seen struggle was trying to do too much. The best ones had ruthless focus — one customer type, one problem, one channel. Expand after you've won something first.</p>` },
      { tag:'Revenue', title:'How to Get Your First 10 Customers Without a Marketing Budget', desc:'The exact playbook used by founders who bootstrapped their first revenue from zero.', time:'9 min', url:'https://dev.to/search?q=first+customers+bootstrap+startup',
        content:`<p>Your first 10 customers don't come from ads, SEO or social media. They come from you doing things that don't scale. Here's the playbook.</p><p><strong>Start with your personal network.</strong> Write down every person you know who might have the problem you're solving. Not everyone — specifically people with the problem. Message them personally. Not a pitch — a genuine question about whether they've experienced this problem and how they're dealing with it.</p><p><strong>Find where your customers already gather.</strong> Reddit communities, Slack groups, Discord servers, LinkedIn groups, industry events. Go there and be genuinely helpful. Answer questions. Provide value. Mention what you're building only when directly relevant.</p><p><strong>The cold email formula that works.</strong> One sentence on who you are. One sentence on why you're reaching out specifically to them. One sentence on what you've built. One question they can answer yes or no. No pitch decks, no feature lists, no long emails.</p><p><strong>Give it away to the first few.</strong> Your first customers are beta testers and case studies. Trade free access for their time and feedback. The data and testimonials you get are worth more than any early revenue.</p>` },
      { tag:'Growth', title:'The 10 Growth Levers Every Founder Should Know', desc:'A framework for diagnosing why your startup isn\'t growing and what to pull first.', time:'11 min', url:'https://hashnode.com/search?q=startup+growth+levers',
        content:`<p>Most growth problems are actually one of five problems in disguise: you're not reaching enough of the right people, your messaging isn't landing, your onboarding loses people, your product doesn't create enough value, or you haven't found a repeatable channel yet.</p><p><strong>Acquisition:</strong> Where are your best customers coming from? Double that. Stop spending energy on channels that trickle.</p><p><strong>Activation:</strong> What's the single moment when a new user first gets real value from your product? Get every new user to that moment as fast as possible. Remove every step between signup and that moment.</p><p><strong>Retention:</strong> This is the most underrated growth lever. Keeping the customers you have is 5-7x cheaper than acquiring new ones. If you have a retention problem, no amount of acquisition spend will fix your business.</p><p><strong>Revenue:</strong> Most founders underprice. Run a pricing experiment. Raise your price 30% and see what happens to conversion. You'll often find it doesn't change much — meaning you were leaving money on the table.</p><p><strong>Referral:</strong> Happy customers who tell others are the best channel you'll ever have. Build this deliberately. Ask for referrals at the moment of highest satisfaction.</p>` },
    ],
    'investor': [
      { tag:'Strategy', title:'How to Build a Portfolio That Actually Weathers Downturns', desc:'Evidence-based portfolio construction that long-term investors use — not what gets clicks on financial Twitter.', time:'10 min', url:'https://medium.com/search?q=portfolio+construction+long+term+investing',
        content:`<p>The best portfolio isn't the one that performs best in bull markets. It's the one you can hold without panic-selling when things go wrong.</p><p><strong>Asset allocation is 90% of the result.</strong> Academic research consistently shows that asset allocation — how you split between stocks, bonds, real estate, and cash — explains most of your long-term returns and volatility. Stock picking within those categories is mostly noise.</p><p><strong>The case for index funds.</strong> Over any 15-year rolling period, over 90% of actively managed funds underperform their benchmark index. After fees. The math is simple: lower costs compounded over decades dramatically outperform higher costs, even with slightly better gross returns.</p><p><strong>Rebalancing is your friend.</strong> When an asset class has a great year and grows to represent a larger share of your portfolio than intended, rebalancing forces you to sell high and buy low automatically — the opposite of what most investors do emotionally.</p><p><strong>The most dangerous number in investing is "this time is different."</strong> It never is. Markets have recovered from every crash in history. The investors who got rich were the ones who kept buying during crashes, not the ones who timed the market.</p>` },
      { tag:'Mindset', title:'The Psychology of Money: Why Smart People Make Dumb Financial Decisions', desc:'The behavioral economics behind why our instincts about money are almost always wrong.', time:'8 min', url:'https://medium.com/search?q=psychology+of+money+behavioral+finance',
        content:`<p>Your biggest financial enemy isn't inflation, taxes, or a bear market. It's your own brain. Here's why.</p><p><strong>Loss aversion.</strong> Losing $100 feels roughly twice as bad as gaining $100 feels good. This asymmetry causes investors to sell during downturns (locking in losses) and hold winners too long (avoiding the "loss" of giving up potential gains). Being aware of this doesn't eliminate it — you have to build systems that make the emotional decision impossible.</p><p><strong>Recency bias.</strong> We dramatically overweight recent events when predicting the future. A crash makes us think crashes are normal. A bull run makes us think markets always go up. Neither is true.</p><p><strong>Overconfidence.</strong> Studies consistently find that most people believe they're above-average investors. Mathematically, most are wrong. The solution isn't humility — it's rules. Automate your investing so your confident self can't override your rational self.</p><p><strong>The one habit that beats all others:</strong> automate consistent investing regardless of market conditions. The investor who contributes the same amount every month — bull market or bear market — consistently outperforms the investor who tries to time contributions to market conditions.</p>` },
      { tag:'Basics', title:'Index Funds vs. Individual Stocks: The Math Nobody Shows You', desc:'Running the actual numbers on why most stock pickers underperform the market over time.', time:'6 min', url:'https://dev.to/search?q=index+funds+vs+stocks',
        content:`<p>Let's run the numbers, not the narratives.</p><p><strong>The S&P 500 has returned roughly 10% annually over the past century.</strong> After inflation, that's about 7% real return. $10,000 invested at 25 becomes roughly $380,000 at 65 at that rate. That's the baseline you're trying to beat.</p><p><strong>Most stock pickers don't beat it.</strong> Over 15 years, 88% of large-cap active funds underperform the S&P 500 according to SPIVA data. The ones that do outperform in one period don't reliably continue outperforming. Past performance genuinely doesn't predict future performance.</p><p><strong>Costs are the silent killer.</strong> A fund with 1% annual fees versus 0.03% (a typical Vanguard index fund) sounds trivial. But over 40 years, that 0.97% difference costs you roughly 32% of your final portfolio value. That's hundreds of thousands of dollars on a typical retirement account.</p><p><strong>The bottom line:</strong> for most people, most of the time, a total market index fund held consistently over decades will outperform complex stock-picking strategies — with less stress, less time, and lower costs.</p>` },
    ],
    'designer': [
      { tag:'Process', title:'The Design Process That Actually Works (Not What School Taught You)', desc:'How working designers actually approach projects versus the idealized process you learned.', time:'8 min', url:'https://medium.com/search?q=design+process+ux+workflow',
        content:`<p>Design school teaches you a clean, linear process: research → ideate → prototype → test → repeat. Real client work looks nothing like this.</p><p><strong>The real process starts with constraints.</strong> Budget, timeline, technical limitations, stakeholder opinions, brand guidelines — these aren't obstacles to good design, they're the brief. The best designers work with constraints creatively rather than fighting them.</p><p><strong>Research is faster than you think.</strong> You don't need a six-week discovery phase to make good design decisions. Three to five user interviews, a competitive audit, and a review of existing analytics will tell you 80% of what you need to know. Perfect is the enemy of shipped.</p><p><strong>The feedback loop is everything.</strong> Get something in front of real users as fast as possible — even if it's just a sketch on paper. The feedback you get from real people in five minutes will change your design more than two weeks of solo iteration.</p><p><strong>Your first idea is almost never your best idea.</strong> Force yourself to generate at least five different approaches before committing to one direction. The constraints of the brief start to bend in interesting ways once you've exhausted the obvious solutions.</p>` },
      { tag:'Career', title:'How to Build a Design Portfolio That Actually Gets You Hired', desc:'What hiring managers and design leads actually look at — and what they ignore.', time:'9 min', url:'https://hashnode.com/search?q=design+portfolio+hired',
        content:`<p>After hiring dozens of designers and reviewing thousands of portfolios, here's what actually matters.</p><p><strong>Show your thinking, not just your outputs.</strong> A portfolio full of beautiful mockups with no context tells me nothing. Walk me through a problem you solved — what was the brief, what constraints did you work within, what did you try first, why did it fail, what did you ship, and what was the result?</p><p><strong>Three good case studies beat twenty mediocre ones.</strong> Quality and depth beat quantity every time. Pick your three best projects and go deep on each one. Include the messy middle, not just the polished final.</p><p><strong>Show real work when you can.</strong> Student projects are fine early in your career, but real client work — even small projects — demonstrates you can navigate real-world constraints, feedback, and stakeholder dynamics.</p><p><strong>The writing matters as much as the visuals.</strong> How you communicate your thinking in a portfolio tells me how you'll communicate in design reviews, client meetings, and feedback sessions. Write clearly and confidently about your choices.</p><p><strong>What gets portfolios rejected immediately:</strong> no case studies (just mockup galleries), no mobile screenshots for mobile work, dead links, portfolios that are themselves poorly designed, and designs that clearly prioritize aesthetics over usability.</p>` },
      { tag:'Tools', title:'Figma in 2024: The Features Most Designers Still Haven\'t Found', desc:'A roundup of Figma\'s most powerful features that are hiding in plain sight.', time:'6 min', url:'https://dev.to/search?q=figma+tips+features+2024',
        content:`<p>Figma releases features faster than most designers find them. Here are the ones that will change how you work.</p><p><strong>Variables.</strong> Figma's variables feature lets you store values — colors, spacing, text, booleans — and reference them throughout your design. Change one variable and it updates everywhere. This is the difference between a design that takes hours to update and one that takes minutes.</p><p><strong>Dev Mode.</strong> Figma's Dev Mode gives engineers exactly what they need — measurements, properties, code snippets — without cluttering the design view. If you're still screenshotting mockups for handoff, you're doing it the hard way.</p><p><strong>Auto Layout 4.</strong> The latest Auto Layout update added wrapping, negative spacing, and absolute position within frames. Combined with min/max width settings, you can build truly responsive components that behave exactly like CSS flexbox.</p><p><strong>Interactive components.</strong> Prototype states built directly into components mean you can create complex interactions — hover states, toggles, expandable sections — that live inside a single component and work across your entire prototype automatically.</p>` },
    ],
    'fitness coach': [
      { tag:'Science', title:'The Evidence-Based Training Guide: What Actually Builds Muscle', desc:'Cutting through fitness industry myths with what the research actually shows about hypertrophy.', time:'11 min', url:'https://medium.com/search?q=evidence+based+training+muscle+growth',
        content:`<p>The fitness industry is full of bro-science, supplement marketing, and program-selling influencers. Here's what the actual research says.</p><p><strong>Volume is the primary driver of muscle growth.</strong> The number of hard sets you do per muscle per week — typically 10-20 sets for most people — predicts hypertrophy better than any other training variable. Rep ranges, tempo, and specific exercises matter less than getting enough total work done.</p><p><strong>Intensity matters, but not the way you think.</strong> Training to failure or close to it (leaving 1-3 reps in the tank) is necessary for growth. But going to absolute failure on every set of every exercise every workout will slow recovery and increase injury risk. Reserve true failure for the last set of an exercise.</p><p><strong>Progressive overload is the only rule that matters long term.</strong> If you're not getting stronger or doing more volume over months and years, you're not growing. Track your lifts. Increase weight or reps every few sessions. This is boring and simple and it's how everyone who's ever built a great physique did it.</p><p><strong>Protein: 0.7-1g per pound of bodyweight per day.</strong> The ceiling of benefit from protein is well-established. Above about 1g per pound, you're not getting more muscle — you're just expensive urine. Spread it across 3-4 meals for optimal muscle protein synthesis.</p>` },
      { tag:'Business', title:'How to Build a Personal Training Business That Actually Scales', desc:'What separates coaches who struggle for clients from those who have waiting lists.', time:'9 min', url:'https://hashnode.com/search?q=personal+trainer+business+clients',
        content:`<p>Most personal trainers fail not because they're bad coaches, but because they're bad marketers and businesspeople. The fitness knowledge is almost never the bottleneck.</p><p><strong>Your niche is your leverage.</strong> "Personal trainer" is not a niche. "Strength training for women over 40 recovering from injury" is a niche. The narrower your focus, the easier it is to find clients, speak to their specific problems, charge more, and get referrals. Generalists compete on price. Specialists set their price.</p><p><strong>Results are your marketing.</strong> Document client transformations. Before and after photos. Screenshots of messages from clients about how their life changed. Not just physical — energy, confidence, performance at work. These stories are worth more than any ad you'll ever run.</p><p><strong>Online coaching 10x's your income ceiling.</strong> One-on-one in-person training has a hard ceiling — there are only so many hours in a day. Online coaching via app or program lets you work with 10x the clients at 50-70% of the price, netting dramatically more per hour of your time.</p><p><strong>The referral flywheel.</strong> At the end of every client's most successful month, ask: "Do you know anyone who wants results like this?" That's it. Simple, direct, and it works because you're asking when the client is most satisfied.</p>` },
      { tag:'Nutrition', title:'Nutrition for Performance: What High Achievers Actually Eat', desc:'What the research and elite performers actually do about nutrition versus what gets sold to you.', time:'7 min', url:'https://medium.com/search?q=nutrition+performance+evidence+based',
        content:`<p>The nutrition industry runs on complexity and confusion. The actual science of eating for performance is surprisingly simple.</p><p><strong>Protein and total calories are 80% of the game.</strong> Hit 0.7-1g of protein per pound of bodyweight. Eat at a slight surplus to gain muscle (200-300 calories over maintenance) or a moderate deficit to lose fat (400-600 calories under maintenance). Everything else — meal timing, food quality within calories, supplements — is the remaining 20%.</p><p><strong>Meal timing matters less than total intake.</strong> The "anabolic window" myth — that you must eat protein within 30 minutes of training — is largely debunked. Total daily protein intake matters far more than when you consume it. That said, spreading protein across 3-4 meals does optimize muscle protein synthesis compared to eating it all at once.</p><p><strong>Sleep is nutrition.</strong> Poor sleep increases cortisol, decreases testosterone, impairs glucose metabolism, and increases appetite — especially for calorie-dense foods. If you're sleeping 5-6 hours and wondering why your nutrition isn't working, you've found your answer.</p>` },
    ],
    'content creator': [
      { tag:'Growth', title:'The Algorithm in 2024: What Actually Gets Content Seen', desc:'A realistic breakdown of how each major platform\'s algorithm works and how to work with it.', time:'10 min', url:'https://medium.com/search?q=content+creator+algorithm+growth+2024',
        content:`<p>Every platform has a different algorithm, but they all optimize for the same thing: keeping users on the platform as long as possible. Here's how that translates into what gets promoted.</p><p><strong>TikTok / Reels / Shorts:</strong> The first 3 seconds determine everything. If people swipe away immediately, the algorithm buries the video. If they watch to the end, it gets pushed to a wider audience. Completion rate is the most important metric. This means: front-load the value. Start with the most interesting moment, not a preamble.</p><p><strong>YouTube long form:</strong> Click-through rate × average view duration = distribution. A thumbnail and title that gets clicks but disappoints viewers will be punished harder than a video that fewer people click but everyone watches completely. Under-promise and over-deliver.</p><p><strong>Instagram:</strong> Saves and shares are weighted more heavily than likes and comments. Content that people save to reference later — tutorials, tips, information — gets distributed more than content that just gets a quick like.</p><p><strong>The universal truth:</strong> consistency beats virality. Creators who post consistently for 12+ months outperform creators who post sporadically hoping for a hit. The algorithm rewards reliable supply. Your audience wants to know when to expect you.</p>` },
      { tag:'Monetization', title:'How Creators Actually Make Money (The Real Numbers)', desc:'Transparent breakdown of every revenue stream available to creators and realistic income expectations.', time:'8 min', url:'https://hashnode.com/search?q=content+creator+monetization+income',
        content:`<p>The "I make $50K/month as a creator" headlines are real but misleading. Here's what the actual monetization landscape looks like.</p><p><strong>Ad revenue is the worst revenue.</strong> YouTube pays $2-8 CPM (per 1,000 views) depending on niche. A video with 100,000 views might earn $200-800. That sounds like a lot until you divide by the hours spent creating it. Ad revenue is a bonus, not a business model.</p><p><strong>Brand deals are where the money is.</strong> A creator with 50,000 highly engaged followers in a specific niche can charge $1,000-5,000 per integration. The key word is engaged — brands increasingly care about comment quality and conversion over raw follower count.</p><p><strong>Digital products are the highest margin.</strong> Courses, presets, templates, ebooks — you make them once and sell them repeatedly. A $97 course sold to 1,000 people is $97,000 with no ongoing cost of goods. The best creator businesses are essentially media companies with a software product attached.</p><p><strong>Community / subscription.</strong> Patreon, Substack, Discord memberships. Predictable recurring revenue from your most engaged fans. 1,000 true fans paying $10/month is $120,000/year. More achievable than it sounds once you've built real trust with your audience.</p>` },
      { tag:'Strategy', title:'Building in Public: Why Sharing Your Process Is Your Best Growth Strategy', desc:'Why showing your work — including failures — builds audiences faster than polished content.', time:'6 min', url:'https://dev.to/search?q=building+in+public+content+strategy',
        content:`<p>The most counterintuitive growth strategy for creators: show your work before it's good.</p><p><strong>People root for journeys, not destinations.</strong> A perfectly polished account of someone who has already succeeded is less compelling than watching someone figure it out in real time. The struggle creates connection. The vulnerability creates trust.</p><p><strong>Building in public creates content from thin air.</strong> Instead of waiting for something to be finished to share it, every step of the process becomes content. Your research, your experiments, your mistakes, your pivots — all of it is interesting to people on a similar path.</p><p><strong>The compounding effect.</strong> When you've documented your journey publicly, you create a body of work that new followers can binge. Someone who finds you a year from now can read your entire journey from the beginning. That's a relationship accelerator that polished highlight-reel content can't match.</p><p><strong>The best accounts to study:</strong> look for creators who share their revenue numbers, their failed experiments, their decision-making process. These accounts consistently outgrow peers with better production quality because they offer something rare: genuine transparency.</p>` },
    ],
    'default': [
      { tag:'Mindset', title:'The One Habit That Separates People Who Achieve Their Goals From Those Who Don\'t', desc:'It\'s not motivation, discipline, or talent. It\'s something far simpler.', time:'6 min', url:'https://medium.com/search?q=habits+goals+achievement+mindset',
        content:`<p>After studying performance psychology and working with high achievers across dozens of fields, one habit appears more reliably than any other: they review their goals daily.</p><p>Not in a vision-board, manifest-it way. In a clear-eyed, practical way: what is the goal, what does progress look like today, what specifically am I going to do about it before the day ends?</p><p><strong>Why this works:</strong> goals that stay in your head are vague. Goals you write down and read daily get clarified over time. You start to notice when your daily actions don't align with your stated priorities. You catch drift before it becomes permanent.</p><p><strong>The implementation:</strong> write your top goal at the top of a page every morning. Write one specific action you'll take today. Write one thing you learned or accomplished yesterday. Do this for 30 days. The goal clarity and follow-through you develop will compound into results that surprise you.</p>` },
      { tag:'Learning', title:'How to Learn Anything Faster: The Science of Skill Acquisition', desc:'What cognitive science actually says about the fastest path from beginner to competent.', time:'8 min', url:'https://medium.com/search?q=learning+faster+skill+acquisition+science',
        content:`<p>Most people learn new skills slowly because they practice in the wrong way. Here's what the research on expertise actually says.</p><p><strong>Deliberate practice, not just practice.</strong> The 10,000-hour rule is a misreading of the research. What produces expertise is deliberate practice — practice specifically designed to push past your current comfort zone, with immediate feedback, focused on your weakest areas. An hour of deliberate practice beats five hours of comfortable repetition.</p><p><strong>The spacing effect.</strong> Information reviewed at increasing intervals (today, tomorrow, next week, next month) is retained far better than information crammed in one session. This is why flashcard apps that use spaced repetition produce dramatically better recall than rereading notes.</p><p><strong>Retrieval beats review.</strong> Testing yourself on information — trying to recall it rather than just re-reading it — produces 2-3x better long-term retention. Don't just read about what you're learning. Explain it out loud, teach it to someone, or quiz yourself without looking at notes.</p><p><strong>Interleaving accelerates transfer.</strong> Mixing different types of problems in practice — rather than drilling one type at a time — feels harder but produces better real-world performance. This is why problem-sets that vary topics produce better exam results than blocked practice on individual topics.</p>` },
      { tag:'Focus', title:'Deep Work: How to Produce More in Less Time', desc:'Cal Newport\'s framework for doing your best work in a distracted world — the practical version.', time:'7 min', url:'https://medium.com/search?q=deep+work+focus+productivity',
        content:`<p>The ability to focus intensely on cognitively demanding tasks — what Cal Newport calls deep work — is simultaneously becoming more valuable and more rare. Here's how to cultivate it.</p><p><strong>Schedule deep work blocks.</strong> Don't hope for focused time to appear. Block it on your calendar like an external meeting. 2-4 hours of protected, distraction-free time is worth more than a full day of fragmented, interrupted work.</p><p><strong>Embrace boredom.</strong> The ability to focus deeply is a skill that atrophies if you constantly reach for your phone during any moment of downtime. Practice tolerating boredom. The urge to distract yourself is strongest right before a breakthrough.</p><p><strong>Batch shallow work.</strong> Email, messages, admin, meetings — these are necessary but cognitively shallow. Batch them into specific windows rather than letting them interrupt deep work throughout the day. A 1-hour email block at 11am and 4pm is more effective than checking email every 20 minutes.</p><p><strong>Measure output, not time.</strong> Instead of tracking how many hours you sat at your desk, track what you actually produced. This simple shift creates a feedback loop that quickly reveals which habits and environments produce your best work.</p>` },
    ]
  };

  // Score each topic against goal + signals
  const topicKeys = {
    'software engineer': ['software','engineer','coder','developer','programmer','coding','javascript','python','react','tech'],
    'entrepreneur': ['entrepreneur','startup','business','founder','company','venture','build','hustle'],
    'investor': ['investor','invest','finance','trading','stock','fund','portfolio','wealth','money','crypto'],
    'designer': ['designer','design','ux','ui','graphic','brand','creative','figma','visual'],
    'fitness coach': ['fitness','gym','workout','bodybuilding','health','nutrition','training','coach','exercise'],
    'content creator': ['content','creator','youtube','tiktok','instagram','influencer','media','viral','audience'],
  };

  let bestKey = 'default';
  let bestScore = 0;

  for (const [key, keys] of Object.entries(topicKeys)) {
    let score = 0;
    for (const k of keys) {
      if (g.includes(k)) score += 3;
    }
    for (const sig of topSignals) {
      for (const k of keys) {
        if (sig.includes(k) || k.includes(sig)) score += 1;
      }
    }
    if (score > bestScore) { bestScore = score; bestKey = key; }
  }

  // Get articles for best match, fall back to default
  const articles = articleLibrary[bestKey] || articleLibrary['default'];

  // Shuffle slightly based on signals for variety
  const shuffled = [...articles].sort(() => topSignals.length % 2 === 0 ? 0.5 - Math.random() : Math.random() - 0.5);

  res.status(200).json({ articles: shuffled.slice(0, 3) });
}
